# Generated by Django 4.2.7 on 2023-12-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='person',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
